[package]
name = "astral_rust_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
easytier = { path = "./easytier" }

lazy_static = "1"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
uuid = "1"
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
